name: Publish to Maven Central

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'corretto'
          java-version-file: .java-version
          cache: 'gradle'

      - name: Run tests
        run: ./gradlew test

      - name: Publish to Maven Central
        run: ./gradlew publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SERVER_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SERVER_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
